(function() {var implementors = {};
implementors["lzma_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lzma_sys/struct.lzma_options_lzma.html\" title=\"struct lzma_sys::lzma_options_lzma\">lzma_options_lzma</a>",synthetic:false,types:["lzma_sys::lzma_options_lzma"]},];
implementors["xz2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"xz2/stream/enum.Action.html\" title=\"enum xz2::stream::Action\">Action</a>",synthetic:false,types:["xz2::stream::Action"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"xz2/stream/enum.Status.html\" title=\"enum xz2::stream::Status\">Status</a>",synthetic:false,types:["xz2::stream::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"xz2/stream/enum.Check.html\" title=\"enum xz2::stream::Check\">Check</a>",synthetic:false,types:["xz2::stream::Check"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"xz2/stream/enum.Mode.html\" title=\"enum xz2::stream::Mode\">Mode</a>",synthetic:false,types:["xz2::stream::Mode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"xz2/stream/enum.MatchFinder.html\" title=\"enum xz2::stream::MatchFinder\">MatchFinder</a>",synthetic:false,types:["xz2::stream::MatchFinder"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()